### ISSUE TITLE
'Try now' button should link to a client picker these days

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix.org#1027]

**Comment by MadLittleMods** [comment]
Related discussion: 

> I have totally forgotton how to use `matrix.org` in a browser, the matrix.org site asks me what client i want to use, when i just want to use my browser
>
> https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$ZTQ4XWQyVebujUa7blCN_lHD1RZ9kyqEPy3ZDeN7yqc?via=matrix.org&via=libera.chat&via=privacytools.io

**Comment by MTRNord** [comment]
Result of a client market share discussion in a internal chat room at work is that this link may bias that market share as news people for example get missguided to consider element the main client or even to "be" matrix as the clients page is significantly harder to find currently. (even I knowing it exists have a hard time to find it each time I need it).

**Comment by afranke** [comment]
While trying to address this, I found out #924 from last January is what put us in this situation. It seems it was heading in the opposite direction of what we actually want. Just reverting doesn’t quite achieve the issue title either, as [the page it was linking to before](https://matrix.org/try-now/) still features Element prominently and doesn’t have a picker, but it does have a link to [the Try Matrix Now page](https://matrix.org/docs/projects/try-matrix-now/) which has more choice.

The homepage on the other hand also has a *Try Matrix* link that sends to the Try Matrix Now page.

Shall I make the navbar link point to Try Matrix Now as well?

**Comment by MadLittleMods** [comment]
The current `Try Now` button in the main navigation has been invisible to me this whole time. I looked at that [PR](https://github.com/matrix-org/matrix.org/pull/924) and had to visually scan the page 3 times before I saw it. Just anecdotal and perhaps this was because when I tried `Try Now` in the main navigation didn't get me to where I wanted.

I have been always having to go to **Discover** -> **Try Matrix** in the sub-navigation. But this is just insider knowledge that took me a while to figure out I needed when reviewing all of the new Matrix clients people are adding in the PR reviews. 

> Shall I make the navbar link point to Try Matrix Now as well?

I'd say go for it! That seems what this issue is aiming for 👍

Separately improving the onboarding of that page which https://github.com/matrix-org/matrix.org/pull/924 was going for sounds great!

**Comment by afranke** [comment]
> [the page it was linking to before](https://matrix.org/try-now/) still features Element prominently and doesn’t have a picker

That page still exists but is not linked to from anywhere on the website now. Can we just remove it or are we worried about links from the outside?
