### ISSUE TITLE
Add https://fort.kickass.systems/git/rrix/matrix-client

### ISSUE THREAD

**Issue by Matrixcoffee** [matrix-org/matrix.org#109]
An emacs Matrix client.

Ping @rrix

**Comment by rrix** [comment]
See following issues for background:
- matrix-org/matrix-doc#877 
- melpa/melpa#4698 
- jgkamat/matrix-client-legacy-el#3

I would prefer not, given it's current unmaintained status; @jgkamat was working on maintaining a fork going forward, if they are interested in supporting it and eventually re-adding it to MELPA on their master, I'd prefer that, rather than pointing people to a version with some very nasty unaddressed bugs and architectural problems.

**Comment by Matrixcoffee** [comment]
I see. Closing this then. Thanks for responding.

**Comment by alphapapa** [comment]
FYI, Jay and I have "de-legacy-ized" the client and intend to maintain it going forward.  The repo has moved to https://github.com/jgkamat/matrix-client-el  We're not sure when we'll put it on MELPA, but the client is stable and usable.  It also recently gained the ability to load room history, which makes it much more useful.  Thanks to Ryan for providing the foundation and showing the way!
