### ISSUE TITLE
Create a more nontechnical-people friendly introduction page

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/matrix.org#1117]
#### Is your feature request related to a problem? Please describe.
Currently, when going to matrix.org, and clicking on "learn more", you encounter https://matrix.org/docs/guides/introduction, which is a technical introduction to matrix.

However, i think that this page does not much to introduce or give gotchas to people who come from all over, it does not illustrate what matrix is all about. 

#### Describe the solution you'd like
I'd like to see something along the lines of a visual introduction to matrix, illustrating the core concepts (federation, rooms, and encryption), talking about fundamental differences with other platforms, and then giving pokes for how to start (clients, bots, hosting, etc.)

(the above is just a suggestion on how to potentially handle this)

This could be done with something as simple as what [mastodon](https://joinmastodon.org/) does, or as extensive and extravagant as what [filecoin](https://filecoin.io/) does.

Also, note; the current explanation of how rooms and stateres works like is a very technical explanation, i'm asking for something that's more easily digestible, so to say.

**Comment by thibaultamartin** [comment]
@ShadowJonathan does https://matrix.turbo.fish/docs fit the bill for you?

**Comment by ShadowJonathan** [comment]
Not exactly, while it does help people get introduced to matrix, it doesn't explain concepts such as rooms, which is probably the single most important concept within matrix.

**Comment by thibaultamartin** [comment]
Did you check out https://matrix.turbo.fish/docs/technical/rooms_and_events/? I meant the doc as a whole :)

**Comment by ShadowJonathan** [comment]
That one is under the technical documentation, this is explicitly about introducing non-technical people to matrix's concepts.

**Comment by thibaultamartin** [comment]
I believe this could be a matter of mislabeling "Technical documentation". The documentation is not really that technical, it's mostly about Matrix concepts themselves (what is a client, homeserver, appservice, room, event…) and doesn't go into technical details.

I absolutely want to leave everything too technical either to the spec or to implementations docs (e.g. the Synapse docs). Having them on matrix.org would result in them getting out of sync pretty quickly for no good reason.

Would it make sense for you if that section was renamed "Matrix concepts" rather than "Technical docs"?

**Comment by ShadowJonathan** [comment]
> Would it make sense for you if that section was renamed "Matrix concepts" rather than "Technical docs"?

Yes, I think that would work much better.

**Comment by thibaultamartin** [comment]
Fixed, will be deployed on the preview in a few minutes
