### ISSUE TITLE
Feature matrix is missing versions, URI schemes, knocking

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix.org#1139]
Page in question: https://matrix.org/clients-matrix/ 

Missing features:

* which software version is being considered in the Matrix as not/including the features listed
* Matrix URI scheme support is missing and something I am interested in
* knocking support was introduced in room version 7 / Matrix 1.1, but it's not mentioned on the feature matrix.

**Comment by Mikaela** [comment]
Another missing feature is user pills ala Element (iOS): https://github.com/vector-im/element-ios/issues/3526

**Comment by thibaultamartin** [comment]
The matrix clients matrix no longer exists. It's extremely difficult to make a responsive version of such a large table, which is why we went with the cards + filters. Filters should be enough to allow someone to pick a client that works best for them.

With that said, the url should route people to /ecosystem/clients (opened #1886 to keep track of it)
