### ISSUE TITLE
Update Feature of Element Android in https://matrix.org/clients-matrix/ 

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix.org#1236]
"Send stickers" and "voip" are now supported, so the Feature table of https://matrix.org/clients-matrix/ has to be updated.

Not sure about "Room tag showing" and "Room tag editing". If it's adding rooms to favorite and low priority (which uses room tags), it's also supported. If this is something else, like adding any tag to a room, I do now how to do this on Element web, which claims it's supported.

Happy to learn more about this.

**Comment by opusforlife2** [comment]
The table seems to be updated on an ad hoc basis. Can some aspect of it be automated? Like periodically running a feature test suite on all clients (maybe when they release a new stable version) which results in updating this table?

Right now, the feature support across many clients is quite fragmented. It would be very helpful to have an up-to-date bird's eye view of the situation so that users can make informed choices about which client(s) to use.

**Comment by thibaultamartin** [comment]
Clients are no longer split by platform on the new website
