### ISSUE TITLE
Rework the Bridges page

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1539]
## Goal of the page

- Convince everyday people that Matrix is not [XKCD1810](https://xkcd.com/1810/) and that they can find friends even when using Matrix
- Convince community managers that their community can progressively transition to Matrix thanks to bridges, without any hard split
- Make developers want to create new bridges for their favourite platform
- Convince entrepreneurs that interoperability is at the core of Matrix and already works

## Content of the page

The bridges page contains:
- An introduction section of what is a bridge, and what type of bridges exist (same as https://matrix.org/bridges/)
- A table of content
- One section per platform Matrix has bridges for (e.g. Slack, Discord, IRC...). We expect the number of platforms to be significant (there are currently about 30 platforms listed on https://matrix.org/bridges/)
- In each section
- a table of all known bridges implementation with their name, maintainer, link to documentation, last release date, maturity, licence and a list of features (TBD) the bridge supports (✅ / ❌ / string).

While Matrix has a fixed set of features, platforms don't all support the same things (e.g. Slack and Discord support threads, IRC doesn't). We assume that when people are on Matrix.org to look for a bridge, they know the Matrix features and are mostly interested in what features of the target platform are supported.

We need to list the features for the following platforms:
- [ ] Slack
- [ ] Discord
- [ ] IRC
- [ ] Google Chat
- [ ] Tencent QQ
- [ ] WeChat
- [ ] WhatsApp
- [ ] Mumble
- [ ] SMS
- [ ] Skype
- [ ] Email
- [ ] LinkedIn Messaging
- [ ] Facebook Messenger
- [ ] iMessage
- [ ] KakaoTalk
- [ ] Mattermost
- [ ] libpurple
- [ ] GroupMe
- [ ] Google Hangouts (platform closed by Google?)
- [ ] LINE
- [ ] Instagram
- [ ] Signal
- [ ] Telegram
- [ ] Twitter
- [ ] Tox
- [ ] Mastodon
- [ ] Gitter

**Comment by thibaultamartin** [comment]
We also need to list if the bridge requires
- to be admin of the homeserver to deploy it (for example this is not the case for relaybot bridges)
- to be admin on the platform you bridge to (not all bridges _technically_ require it, but that might be a violation of the platform ToS)

We need:
- A clear explanation of what a bridge even is
- A clear explanation of the different bridges types
- For each platform, the list of implementations (e.g. matrix-appservice-x and mautrix-x), and for each implementation what feature is implemented (formated text, replies, typing notifications, read receipts, threads…). Of course, this will vary depending on the platform you bridge to

**Comment by thibaultamartin** [comment]
Matrix of features the various third party platforms support: https://docs.google.com/spreadsheets/d/19VpeLqW-9Nign3f6wTedwVanRjKc5fTm1bzvasvCZSo/edit

**Comment by thibaultamartin** [comment]
For the "each platform", I believe we should have a tiled view of each platform we know we have bridges for (similar to what we do on gatsby matrix.org, maybe with a change on hover to make it more obvious that those are links?)

![image](https://user-images.githubusercontent.com/1688309/211294429-da8f65c8-9e0b-48f1-b770-4359a1ab3b5f.png)

Clicking on the logo of the platform leads to its own page.

Each platform's page then needs to have its list of implementations, the privileges required to deploy the bridge (technical admin on the Matrix homeserver, admin on the third-party platform), the features of the platform supported by each implementation, a status (Obsolete, Alpha, Beta, Stable) and a link to the repository.

Also welcome:
- a link back to the "bridges root" page 
- the different types of bridges, and their impact on privileges required

**Comment by HarHarLinks** [comment]
I ran into this wall again trying to look up projects today, hence I want to note my experience so you may consider it in your redesign.

Part of Matrix is a strong notion of interoperability and integration with all kinds of 3rd party services, additional rich functionality for chat, and even non-chat apps. This is reflected by more or less vaguely defined classification which most prominently include "bridges", "bots", "widgets". These types of services are (not stably per the spec, but still) known as "integrations" and some experimental integration managers exist that allow users to manage them in their rooms. The concept of chat bots is very old and well known ("the actor behind this account is some kind of automation"), while perhaps widgets are less so, and bridges play perhaps their most prominent role in this ecosystem as connecting chat networks to each other is one of the core arguments Matrix tries to make for itself as today we have some fairly stable bridges that are fairly well used yet the concept isn't so common on other services which tend to be silos instead. On the flipside, there are very clear definitions in the spec about the different APIs, including client-server, server-server, and application services.

Often times, what to the user appears to be a bridge/bot/widget can be implemented in many different ways. For example a ping bot may be implemented using the [C2S](https://github.com/maubot/echo) or [appservice](https://codeberg.org/cel2/pingbot-appservice-rs) API. An RSS bridge may use the [appservice](https://github.com/matrix-org/matrix-hookshot/) or [C2S](https://github.com/matrix-org/go-neb#rss-bot) API. Widgets may use the [widget API](https://github.com/vector-im/element-web/tree/develop/src/vector/jitsi) or can simply be static embeds. Some things can be [clients and widgets at the same time](https://github.com/vector-im/element-call).
Conclusion: The type of integration does not translate to the type of API used.

Further, it is often hard to put an integration into a single category unambiguously. There are [bridges that can be configured through widgets](https://github.com/matrix-org/matrix-hookshot/) and there are [widgets that include a bot that one may as well classify also as a bridge](https://github.com/nordeck/matrix-meetings). There are [clients that the current website classifies as bridges](https://gitter.im). There are cases where it's unclear whether it's [a bridge](https://matrix.org/bridges/#rss) or [a bot](https://matrix.org/docs/projects/bot/feedbot).
Conclusion: Integrations can hardly be fenced of so clearly that they can be put into a single one of the 3 categories each. At best, some few categories can be defined well enough to do it, such as bridges meaning exclusively "chat-to-chat".

That's a lot of backstory for the point I'm trying to make. [I went on matrix.org today to find a list of RSS integrations](https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$_cZyb-nb6BZbkBE9-Qy2yY0EGpZD1_nHM_S1jNfVACg?via=matrix.org&via=element.io&via=envs.net). I went by bridges as I know that hookshot ("A bridge between Matrix and multiple project management services, such as GitHub, GitLab and JIRA.") supports feeds, however couldn't find anything save for 1 project in the RSS category. Hookshot isn't on the website at all (hey, at least it isn't in the wrong category?).

A clear goal for the website in my opinion should be to enable users to actually learn and find things. Therefore (ideally) it needs to be as complete and up to date as possible while at the same time well structured and searchable.
My suggestion with regards to bridges (and integrations) is what I've already hinted at:
- the structure must not follow the technical view (e.g. which API), but the view of the user who is looking at the website so s/he can search in the right place
- many points already made in previous comments
  - does it require admin access to use this integration, because it must be registered as an appservice?
- sub categories of "integrations" such as "bridges" can only exist if there is a clear way to define it
  - the bridges page as it is today cannot exist. it would need to be chat-to-chat bridges
  - website maintainers must take care to keep to these criteria
  - in some cases this is not possible
    - is a wolframalpha bot a bot? no, because it bridges to a 3rd party service
    - what categories do widgets with bots and bridges with widgets go in?
- the rest must be in a catch-all "integrations" page that can be filtered by objective attributes rather than subjective views

**Comment by thibaultamartin** [comment]
Thanks for this comment @HarHarLinks, this is very useful during the redesign phase. All of these make sense and I agree with most of them. I quite like the idea of splitting "chat bridges" and "integrations". I wonder to what extent "integrations" would end up eating the "bots" section entirely, but it remains a pragmatic way to split things.

**Comment by HarHarLinks** [comment]
An important aspect of the catch-all integrations page

> eating the "bots" section entirely

would be to still communicate to the onlooker that this is where to find "bots" and other well-known alternative names for things that are collected here. That is due to my earlier point

> The concept of chat bots is very old and well known ("the actor behind this account is some kind of automation")

where a user from a different context that may use alternative names or categorization schemes comes looking at the site by these specific keywords.

Overall, have you looked at how other products that are comparable with Matrix and also have some concept of integrations handle this in regard of communication with the user?

**Comment by thibaultamartin** [comment]
Trying to give some brain time to this issue, I agree that chat-to-chat bridges and integrations should be distinct pages. For the chat-to-chat bridges it's pretty much sorted out: a grid of platforms to bridge to, and for each one of them you're brought to the list of existing bridges for that platform.

Now for the integrations part I quite like the idea in theory, but it can end up being pretty messy and not necessarily more readable for people browsing this page. How to display the various bots, non-chat bridges, widgets etc in a structured way so that people can find what they're looking for?

Ideas welcome, while I spend some time on it myself too :)
