### ISSUE TITLE
Weird hidden text in blog section titles

### ISSUE THREAD

**Issue by tgr** [matrix-org/matrix.org#1605]
A snippet from a [blog post](https://matrix.org/blog/2023/01/03/matrix-community-year-in-review-2022):
![Screenshot Capture - 2023-01-06 - 14-06-05](https://user-images.githubusercontent.com/145412/211108058-80842f08-5fd5-410c-85c2-0b21e4d0d68f.png)

After I (accidentally) click on the section title, a new paragraph (in this case, with a link to the tool that's the subject of the section) shows up:
![Screenshot Capture - 2023-01-06 - 14-07-56](https://user-images.githubusercontent.com/145412/211108250-21e3c923-2ebf-4221-9079-77cba9ab34a0.png)

I can't imagine the point of this. If the extra information is useful (it seems to be, especially the occasional link), it should either not be hidden in the first place, or there should be some indication that there is something to be un-hidden.

**Comment by AshishPandagre** [comment]
Hey, so I was exploring that particular blog link you mentioned and noticed that the titles are enclosed in a [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) tag. 
That's why the content is hidden by default, and when we click them the content is visible to us.

![image](https://user-images.githubusercontent.com/53047854/215756645-2ca805b9-f443-4e83-9ba7-f95235c61460.png)

![image](https://user-images.githubusercontent.com/53047854/215756876-63ec7012-a2c0-456f-842d-a01d26dce973.png)
