### ISSUE TITLE
Legacy spec versions went missing

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.org#1879]
The URLs in https://spec.matrix.org/v1.7/changelog/#historical-versions are 404s

**Comment by thibaultamartin** [comment]
@laurencegill could it be something that's been forgotten in the move to CF?

**Comment by laurencegill** [comment]
Quite possibly, although I'm a little confused why these links point at matrix.org rather than being relative links to spec.matrix.org?

For example, **Push Gateway API** is a link to https://matrix.org/docs/spec/push_gateway/r0.1.0.html (broken) rather than to 
https://spec.matrix.org/legacy/push_gateway/r0.1.1.html (working)

**Comment by richvdh** [comment]
> Quite possibly, although I'm a little confused why these links point at matrix.org rather than being relative links to spec.matrix.org?

Because *all* of the spec used to live at `matrix.org/docs/spec`; and those "legacy versions" *still* lived there until [very recently](https://github.com/matrix-org/matrix.org/issues/1725#issuecomment-1531808741).

In theory we *could* go through all the old changelogs which point to `matrix.org`, but regenerating them all is something of a pain in the butt, and anyway there are probably other links which we don't know about which we'd rather not break.
