### ISSUE TITLE
Limit the number of items returned in the atom feed

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1918]
Some websites seem to limit it to 10-20 items. At the moment we return all the articles, and that's quite a lot.

I need to assess whether it's a common/best practice, and it's then simple to implement in the atom feed template.

**Comment by dhenneke** [comment]
I have the same issue. I use Feedly and they don't crawl the feed since the switch to the new website. It really seems to be related to the size of the `atom.xml` because it starts to work again when I manually edit the file to only keep 10 entries, upload it to a private server, and import it from there. I can reproduce that there is not a special entry in it that breaks it but just the raw amount of data that is too much.

If there is a need for a feed with _all_ entries, a compromise could be to provide one feed with all entries (`atom.full.xml` or `atom.archive.xml`) and one with only the latest 10-20 entries (`atom.xml`). Or we could try to implement atom feed-pagination as described in [RFC 5005](https://www.rfc-editor.org/rfc/rfc5005#section-3) 😅.

**Comment by JokerGermany** [comment]
f you limit the Feed., pls add a Feed for all entries, too.

**Comment by clokep** [comment]
Maybe an option would be to have a limited number with full content or all articles but only titles?

**Comment by JokerGermany** [comment]
A feed of all articles but only titles sounds promising
