### ISSUE TITLE
Update Element Client link to github repo 

### ISSUE THREAD

**Issue by alexisbatyk** [matrix-org/matrix.org#2112]
the new link is: 
https://github.com/element-hq

from the old repo:
ℹ️ Our vector-im GitHub organisation has been renamed to [element-hq](https://github.com/element-hq). Nothing has changed on our side, we've called ourselves Element for a long time and now our GitHub org name reflects this.

Links to vector-im org repositories, issues, and PRs, will automatically redirect to the renamed element-hq.

**Comment by MTRNord** [comment]
For the record: The PR #2119 will update the ecosystem pages. For the posts considering the amount of links it is probably sensible to keep them as is since that would be quite a few occurrences to change (almost every twim edition).

If someone from element or foundation has a different opinion on this feel free to reopen it/ping me though :)
