### ISSUE TITLE
Matrix.org has broken the federation connection 

### ISSUE THREAD

**Issue by artenax** [matrix-org/matrix.org#2483]
The default and largest server on the Matrix network has broken the key exchange between messenger users. Users with accounts on matrix.org do not receive the key from their contacts with accounts on other servers, so they cannot decrypt messages. /discardsession does not help.

Users on matrix.org have in chat instead of message text: “unable to decrypt message” (in Element client) and “message could not be decrypted due to missing key” (in Nheko).
Users of any other servers can read messages from matrix.org users - they get the keys.
Communication between users of any other servers goes without problems.

**Comment by roman90sv** [comment]
This problem has existed since at least the end of July.

**Comment by ImMALWARE** [comment]
I also can't get messages from nitro[.]chat user, same problem

**Comment by sigseg5** [comment]
Knock, knock
Who's there?
*Three-letter agency*:
_Create a corral so people don't spread out on uncontrolled servers._

**Comment by ara4n** [comment]
we’re not aware of federation problems on matrix.org atm. generally when other servers can’t federate (eg nitro.chat) it’s because they are coughing up errors to requests from matrix.org for whatever reason, which means they then get marked down - ie a problem on the receiver not the sender.

in order for this bug report to actually be actionable, you may want to:
 * give an example of a server which matrix.org is failing to federate with
 * give details of a request that’s failed (eg client logs for an event that couldn’t be decrypted on the sender & receiver side)

…otherwise we’ll have to close this as unactionable.

**Comment by kegsay** [comment]
> Users on matrix.org have in chat instead of message text: “unable to decrypt message” 

I've been the developer looking at messages which are unable to decrypt (UTD) in the ecosystem. There's a few reasons why this may happen. This typically (though not exclusively) means matrix.org was unable to claim one-time keys (OTKs) for those remote users, or it failed to send room keys, particularly if it _used to work_. This is governed by the endpoints `/keys/claim` for OTKs over both the client-server and federation APIs, and `/sendToDevice` with `m.direct_to_device` for room keys over the client-server API and federation API respectively.

`/discardsession` won't help if these endpoints are not working correctly, which implies a communication problem with your server _for those endpoints_ (given the messages themselves seem to make it there okay, but messages use a different endpoint). Without knowing the server domain, along with the dates/times it happened, we can't help diagnose this any further, but typical reasons I've seen are:
 - those endpoints (particularly `/keys/claim`) times out, which is more likely if you have lots of users on your server,
 - the sending server (in this case matrix.org) is backing off sending to-device messages.
 
However, if you are sending traffic to matrix.org, the backoff timer should be reset, so it's most likely timeouts on `/keys/claim`. This isn't anything to do with matrix.org, it's your server being slow. Assuming this user is on the same server:

> This problem has existed since at least the end of July.

then I would check your logs at the end of July for timeouts/non 2xx status codes for `/keys/claim`. That's basically all I can analyse with the information you've provided unfortunately.

**Comment by artenax** [comment]
So **YOU** have a federation working?
The point of my post was that it looks like the **federation is broken for ALL people**. Since there have been many complaints (and I confirm), including those with private personal servers... Although all of them are from Russia... 

Well, if you don't use the federation... register two accounts on different servers and check the logs. I used a German server.
Prove that federation works...

**Comment by ara4n** [comment]
oh! if you're in Russia (which, of course, you didn't bother to say either here or on HN), then you are probably suffering from your government censoring access to matrix.org.  We *are* aware of folks in Russia being unable to connect to the CS API on matrix.org for the last few weeks, but this is the first we've heard of the SS API being blocked too.

You may wish to complain to your own 3-letter agencies...

**Comment by ara4n** [comment]
Looking at OONI - it doesn't have stats on matrix-federation.matrix.org (https://explorer.ooni.org/domain/matrix-federation.matrix.org?since=2024-08-25&until=2024-09-25&probe_cc=RU) but it does for the CS API: https://explorer.ooni.org/domain/matrix-client.matrix.org?since=2024-08-25&until=2024-09-25&probe_cc=RU

![Screenshot 2024-09-24 at 10 40 58](https://github.com/user-attachments/assets/c4ea1bfc-4c74-473d-999e-7aae837cacdb)

So I'd assume that SS API is impacted too.

The workaround is to use censorship circumvention, as you would on any other service.

Separately, Matrix could do more native censorship circumvention - either via p2p (arewep2pyet.com) or by rearchitecting E2EE so it can bounce transitively via other servers (like plaintext traffic can).  But both of those are long-term projects which just don't exist yet today.

**Comment by artenax** [comment]
matrix-client.matrix.org was blocked recently. But matrix.org works and the messengers that connect to it also work (even though it is not standard). I mean, when communicating within the matrix.org server.
But the connection to the federation was broken earlier.

However, something doesn't add up for you.

I tested under Cloudflare WARP VPN, it is uncensored, although the IP is considered Russian (I think it comes out of Cloudflare servers somewhere from Finland). And there was still no connection to the federation (in app.element.io in the browser). It looks more like a geo block on your side.

You still haven't said if federation is working for you.
I can certainly check under VPN later...

**Comment by kegsay** [comment]
> So YOU have a federation working?

Yes.

**Comment by ara4n** [comment]
As I said:

> we’re not aware of federation problems on matrix.org atm

We are not blocking anything on the matrix.org side, nor are any servers currently defederated.

If you can actually give us something to go on (e.g. the hostname of an impacted server) then we try to understand what's actually going on, but so far this continues to be completely unactionable...

**Comment by skobkin** [comment]
I've just checked from my personal server (`skobk.in`) which is NOT in Russia (although I am) that federation is working.

I've wrote to the chat hosted on `matrix.org` and `matrix.org` users saw that and replied.

But. When I tried to check the key exchange via DM with my friend who has account on `matrix.org` it showed a problem with the key.

Here's my message to her from Nheko:
![image](https://github.com/user-attachments/assets/319ba5bb-becc-4a62-ba4a-a25c04a4a55c)

Here's how she saw my message on mobile:
![image](https://github.com/user-attachments/assets/1c04e7de-9616-4d3b-8859-763d90dafe17)

Here's how I see her reply:
Nheko:
![image](https://github.com/user-attachments/assets/853870a5-3951-46e7-b4db-07d226fdfd21)

Element Web (self-hosted):
![image](https://github.com/user-attachments/assets/b5b58650-fcad-4771-9854-9a5145c76b0a)

@ara4n, @kegsay 
So here's what I personally can conclude:

- The **federation** is **working**.
- There are probably **some issues** with **key exchange**.

I really don't like the attitude of some people who accuse `matrix.org` of something based on nothing. We should probably dig deeper into the issue and try to find out what's really going on instead of pointing fingers at each other.

I can't provide server logs right now. If someone can replicate my experiment, please do that. If not, then I'll try to repeat it later and provide logs myself.

If possible, please reopen he issue so it won't be lost.

**Comment by artenax** [comment]
Well, I managed to create an encrypted room between `@nakity:matrix.org` and `@nakita:matrix.im`
However:
No messages go from matrix.org to matrix.im
But messages are going from matrix.im to matrix.org
Client logs:
[matrix.org.zip](https://github.com/user-attachments/files/17116776/matrix.org.zip)
[matrix.im.zip](https://github.com/user-attachments/files/17116782/matrix.im.zip)

Encryption is a terrible thing, that's why I don't use it. Except for tests.

**Comment by artenax** [comment]
I want to add that I tested it in VPN (or rather, shadowsocks proxy FI/DE) without censorship.
Cloudflare warp vpn (aka 1.1.1.1) and shadowsocks via Cloudflare warp vpn - same results. I think it doesn't matter.
Sessions are not simultaneous, i.e. it's not live chat, but offline messages (I changed browser profiles and restarted it with cache clearing, in the web versions: `app.element.io` and `element.matrix.im`).
Browser: ungoogled-chromium-128.0.6613.137.AppImage

**Comment by artenax** [comment]
I've seen the same problem **before** between transfem.dev (now dead) and matrix.im. That is, without involving communication with matrix.org contacts.
What do you say to that now? Did the NSA ask you to do this?

**Comment by artenax** [comment]
Logically it seems that matrix.im has the problem. But there are complaints on different servers, as you understand.

**Comment by skobkin** [comment]
Small update from me.

After some time, I've got the message from my friend (mentioned above) successfully decrypted on all devices.

I'm not really sure what changed since then :shrug:

**Comment by andreymal** [comment]
Someone from matrix.im invited me to a room, I have no idea what's wrong with it, but `matrix-client.matrix.org` returns error 524 when I'm trying to read it

<sup>(not sure if this is realted to this issue, but this issue was the first link on google)</sup>

<a href="https://github.com/user-attachments/assets/628f6d0f-6900-4ecc-ab6c-69fff31a00e3" target="_blank"><img src="https://github.com/user-attachments/assets/628f6d0f-6900-4ecc-ab6c-69fff31a00e3" width="329" height="176"></a>

**Comment by Loh1917** [comment]
I have same problem with my account on matrix.org and imagisphe.re server too.

**Comment by theo546** [comment]
> ![Снимок экрана от 2024-10-24 12-59-31](https://github.com/user-attachments/assets/8314e891-e55f-46a5-b2b3-110a6b2a06c7) ![Снимок экрана от 2024-10-24 13-02-05](https://github.com/user-attachments/assets/58345fb4-275d-4156-92ce-36d71ff3d06a) I have same problem with my account on matrix.org and imagisphe.re server too. But with other servers (foe sample studichat.de) all is OK.

Oh wow, guess what, I'm the IMAGISPHE.RE admin and was looking for a way to fix this broken federation between IMAGISPHE.RE and matrix.org and it seems like I've reached a dead end.
