### ISSUE TITLE
https://matrix.org/legal/ doesn't link to https://matrix.org/legal/riot-im-cookie-policy/

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix.org#632]

**Comment by benparsons** [comment]
cc @lampholder this is by design, I think?

**Comment by thibaultamartin** [comment]
We don't collect any cookie on the matrix.org website, and I can't think of a way the matrix.org homeserver would store cookies in your browser. Your client will, and I think it's the responsibility of the client to display its cookie policy?

I'd rather not link to Element's cookie policy, since I want the website to remain as vendor-neutral as possible. Please reopen if I missed something in your question

**Comment by aaronraimist** [comment]
Yeah that's fine. At the time Riot/Element's cookie policy was hosted on matrix.org, so it made sense to link it there.
