### ISSUE TITLE
Update favicon to be highres and dark-mode compatible

### ISSUE THREAD

**Issue by 532910** [matrix-org/matrix.org#741]
Please add highres favicon for high-dpi screens.
Firefox preview screenshot for example:

![](https://user-images.githubusercontent.com/14617699/82830936-b886b700-9ebf-11ea-867c-f9f6b8f514dd.png)

And it also should adapt in dark mode since the square braces are dissipated.

![](https://user-images.githubusercontent.com/14617699/172110368-77965c52-bf6f-4020-aa5c-522e79f925f2.png)

**Comment by MadLittleMods** [comment]
I've made a cleaned-up SVG version of the Matrix.org favicon in https://github.com/matrix-org/matrix-public-archive/pull/135. Also since it's an SVG, there is a CSS media query in it to adapt to dark and light mode.

. | Light | Dark
--- | --- | ---
macOS Chrome (retina) | <img width="254" alt="" src="https://user-images.githubusercontent.com/558581/201301038-ba4c80c3-6598-470d-a4a6-b955ba8bcd5a.png"> | <img width="257" alt="" src="https://user-images.githubusercontent.com/558581/201301035-8b687105-c1db-4817-808b-5b738c5ae4f8.png">
Windows 10 Chrome (non-retina) | ![](https://user-images.githubusercontent.com/558581/201300881-7ca98b3a-d7c2-4b16-8810-132f58eb6731.png) | ![](https://user-images.githubusercontent.com/558581/201300888-48bc6340-f189-4ef9-8e55-8a8b4122aaf7.png)


We can probably just use that and run it through https://realfavicongenerator.net/ if we want the rest of the Apple icons, etc. But we should still update use the SVG favicon as the main one.

**Comment by thibaultamartin** [comment]
Fixed, will be deployed on the preview in a a few minutes
