### ISSUE TITLE
Client lists and stuff need rebrand

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/matrix.org#784]
For example 
![Screenshot 2020-07-15 at 15 13 34](https://user-images.githubusercontent.com/19155609/87556380-7b17fc00-c6ae-11ea-9d8b-06971b215b32.png)

**Comment by lufrankland** [comment]
I would also add to this that the "Hosting" tab needs to be updated to have Element rather than the Modular too 
![Screenshot 2020-07-15 at 15 21 11](https://user-images.githubusercontent.com/1331825/87556795-fbd6f800-c6ae-11ea-81c5-6512ce78fc58.png)
[https://matrix.org/hosting/](https://matrix.org/hosting/)

**Comment by lufrankland** [comment]
Furthermore, the following URLs are needing an update:
https://matrix.org/try-now/
https://matrix.org/docs/projects/try-matrix-now/

**Comment by benparsons** [comment]
Clients themselves are updates, thanks @lufrankland for pointing out the need for various other graphics!

**Comment by lufrankland** [comment]
Yeah, I got all the updates but notices it while talking to @Twi1ightSparkle this morning and then found a barrage of pages that need new graphics and/or "Element" branding. If I read correctly too, the Modular Matrix hosting is now Element Hosted so that would also need a little update with the nice new logo :)

**Comment by benparsons** [comment]
fixed various
