### ISSUE TITLE
Feedback widget is distracting / annoying

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.org#809]
The feedback widget that appears lately on all matrix.org page lately is quite distracting / annoying. It lowers my confidence in the site overall, and makes me less likely to share matrix.org pages, as I don't want to inflict it on other people.

While I can understand a desire for feedback, are we actually getting useful signals through this widget? If removing it is not possible, could it be change to a much less distracting icon in the corner that can be expanded, like some other sites use?

<img width="256" alt="" src="https://user-images.githubusercontent.com/558581/130168504-c7eb8128-bddd-4834-9a41-c500d2ebaf79.png">

## Relevant code

 - [`gatsby/static/js/rating.js`](https://github.com/matrix-org/matrix.org/blob/ed8c66b5a178c6c0ed0d81e462d019c09d109445/gatsby/static/js/rating.js)

**Comment by aaronraimist** [comment]
I agree with this. The rating thing is pretty annoying. It pops up on seemingly every single page load and right as I notice it and start to move my mouse over it then it disappears. I can't imagine a 1-5 star rating by itself is even all that useful even if it wasn't annoying.

If you need to collect feedback then maybe something built in to the bottom of the page with both a rating and a text field would be better.

It also seems just premature to add something like this all. There are plenty of issues worth taking care of already posted on GitHub here.

**Comment by MadLittleMods** [comment]
I was curious to check in on how often these ratings are being used so I checked in [Matomo](https://matomo.riot.im/). It looks like there are `1770` rating events in there since it was [first introduced](https://github.com/matrix-org/matrix.org/pull/776) in 2020-07-01.

I was also curious to see which pages are getting less than 5 star ratings but Matomo's interface is a bit infuriating. It seemed like I was getting a bunch of timeouts or no data errors when trying to troubleshoot things, i.e. `Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance.` or when picking a smaller time range, `There is no data for this report.` but after a while and a refresh, things just magically worked. Maybe there is some indexing background process but it would be a lot nicer if they exposed that progress and that is still just a guess.

Eventually I was able to make a segment on `matrix.org` where it only showed visits where a `rating` event happened. Then I could go to the `Event Names` tab and export the data from there to process in a [spreadsheet](https://docs.google.com/spreadsheets/d/1Regz1-VdqPvQqb0_rbEeIxvqVV1kAleHdAHLYoF0lnk/edit#gid=1398812873).


![](https://user-images.githubusercontent.com/558581/130295071-92497374-6071-4816-81eb-a02edfdab018.png)

Here are any page URL's which have more than 3 ratings overall with an average rating of less than 4 ([Matomo source](https://matomo.riot.im/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday&updated=1#?idSite=3&period=range&date=2020-01-01,2021-08-20&category=General_Actions&subcategory=Events_Events&segment=eventCategory%3D%3DRating)). I'm not sure this is that helpful since it probably has a lot of 5-stars skewing this where people had no problem with the page:

 - `/clients-matrix/`: 3.14
 - `/legal/privacy-notice`: 3.25
 - `/docs/guides/whatsapp-bridging-mautrix-whatsapp`: 3.5
 - `/docs/guides`: 3.56
 - `/docs/projects/server/synapse`: 3.62
 - `/docs/projects/try-matrix-now/`: 3.69
 - `/docs/guides/end-to-end-encryption-implementation-guide`: 3.72
 - `/discover/`: 3.73
 - `/try-now/`: 3.87
 - `/docs/develop`: 3.91
 - `/clients/`: 3.93


If we ignore any 5-star ratings ([Matomo source](https://matomo.riot.im/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday&updated=1#?idSite=3&period=range&date=2020-01-01,2021-08-20&category=General_Actions&subcategory=Events_Events&segment=eventCategory%3D%3DRating;eventValue%3C5)):

 - `/try-now/`: 1.6
 - `/docs/guides/end-to-end-encryption-implementation-guide`: 1.85
 - `/docs/projects/server/synapse`: 2
 - `/docs/guides/whatsapp-bridging-mautrix-whatsapp`: 2
 - `/docs/develop`: 2.08
 - `/docs/guides/free-small-matrix-server`: 2.14
 - `/docs/guides/usage-of-the-matrix-js-sdk`: 2.29
 - `/docs/projects/client/element`: 2.33
 - `/clients-matrix/`: 2.4
 - `/foundation/`: 2.4
 - `/matrixlive/`: 2.4
 - `/docs/guides`: 2.43
 - `/docs/projects/try-matrix-now/`: 2.48
 - `/docs/guides/getting-involved`: 2.5
 - `/docs/guides/client-server-api`: 2.5
 - `/clients/`: 2.53
 - `/bridges/`: 2.57
 - `/docs/develop/`: 2.6
 - `/docs/guides/installing-synapse`: 2.71
 - `/docs/projects/try-matrix-now`: 2.73
 - `/blog/2020/09/30/welcoming-gitter-to-matrix`: 2.75
 - `/`: 2.76
 - `/docs/guides/introduction`: 2.82
 - `/docs/projects/client/element-android`: 2.82
 - `/docs/guides/application-services`: 2.83
 - `/docs/guides/types-of-bridging`: 2.83
 - `/faq/`: 3
 - `/discover/`: 3.1
 - `/docs/guides/`: 3.11
 - `/blog/posts`: 3.25
 - `/docs/projects/client/element-ios`: 3.25


I don't know the original intentions of adding the rating system to know if this analysis draws the proper conclusions we were looking for. But thought it was interesting 🌈

**Comment by thibaultamartin** [comment]
Widget has been nuked from orbit in the Zola migration 🚀
